platform :ios, '11.0'
use_frameworks!

target 'Unity-iPhone' do

  # Pods for Unity-iPhone
  source 'https://mixedrealitycloud.visualstudio.com/Mixed%20Reality%20Cloud%20Preview/_git/Mixed%20Reality%20Cloud%20CocoaPod'
  pod 'AzureSpatialAnchors', '1.0.0-release0011'
end
